[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py collectstatic --noinput && gunicorn blog_project.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10